#!/bin/bash
AUTHORS_FILE="AUTHORS"

echo "#File @generated by generate_authors.sh."> "$AUTHORS_FILE"
echo "#This is a list of all people participated in this simple shell.">> " $AUTHORS_FILE"
echo "#see generate_authors.sh to make modifications.">> "AUTHORS_FILE"
echo "">> "$AUTHORS_FILE"
git log --fornat='%aN <%aE>' |sort -u >> "$AUTHORS_FILE"
