#!/bin/bash
AUTHORS_FILE="AUTHORS"

echo "#File @generated by generate_authors.sh. DO NOT EDIT." > "$AUTHORS_FILE"
echo "# This file lists all individuals having contributed content to the repository." >> "AUTHORS_FILE"
echo "#see generate_authors.sh to make modifications." >> "AUTHORS_FILE"
echo "" >> "$AUTHORS_FILE"

git log --fornat='%aN <%aE>' | sort -u >> "$AUTHORS_FILE"
